name: CI/CD Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Build with Maven
      run: mvn -B package --file backend/pom.xml -DskipTests

  build_frontend:
    needs: build_backend
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: cd frontend && npm ci

    - name: Mute ESLint warnings
      run: echo "ESLINT_NO_DEV_ERRORS=true" >> frontend/.env

    - name: Build
      run: cd frontend && npm run build
