name: CI/CD Pipeline

on:
  

jobs:

  build_backend:
    name: 
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 
          cache: maven
  
      - name: 
        run: 
        working-directory:


  build_frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: [build_backend]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 
          cache-dependency-path: 
  
      - name: Install dependencies
        run: 
        working-directory: 
        
      - name: Build frontend
        run:  --no-progress 2>&1 >/dev/null || true # Mutes ESlint warnings
        working-directory: 
