name: CI/CD Workflow

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
              java-version: '11'
              distribution: 'adopt'

        - name: Build with Maven
          run: mvn -B package --file backend/pom.xml

        - name: Setup Node.js environment
          uses: actions/setup-node@v2.4.1
          with:
              node-version: '14'

        - name: Install dependencies for frontend
          run: npm ci --prefix frontend

        - name: Build frontend
          run: npm run build --prefix frontend
