name: CI/CD Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file backend/pom.xml -DskipTests

  build-frontend:
    needs: build-backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.1
      with:
        node-version: '14'

    - name: Install dependencies for frontend
      run: npm ci --prefix frontend

    - name: Build frontend
      run: |
        export ESLINT_NO_DEV_ERRORS=true
        npm run build --prefix frontend
